// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1591.Powerup.subsystems;

import org.usfirst.frc1591.Powerup.Robot;
import org.usfirst.frc1591.Powerup.RobotMap;
import org.usfirst.frc1591.Powerup.commands.*;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.interfaces.Potentiometer;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.AnalogPotentiometer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DigitalInput;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
	
public class Lift extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX liftTalon = RobotMap.liftliftTalon;
    private final DigitalInput heightReachedLimit = RobotMap.liftheightReachedLimit;
    private final DigitalInput reverseEnabledLimit = RobotMap.liftreverseEnabledLimit;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    //Variables
    
    public Lift() {
    	
    }
    
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
     
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
    	spoolIn();
    }
    
    //make the winch spool in to pull the robot up
    public void spoolIn() {
    	
//        SmartDashboard.putData("heightReachedLimit", heightReachedLimit);
    	//false is on
        if (reverseEnabledLimit.get() == false) {
        	liftTalon.set(1);
        }
        else {
        	//when A is pressed, the winch starts to spool in
	    	if (Robot.oi.elevatorStick.getRawButton(1) && (heightReachedLimit.get() == true)) {
	    		liftTalon.set(-1);//set to correct direction at full power PLACEHOLDER
	    	}
	    	//when the robot gets 12 in above the ground, stop the winch
	    	else {
	    		liftTalon.set(0);
	    	}
    	
        }
    }
}

