// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1591.Powerup.commands;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc1591.Powerup.subsystems.*;

/**
 *
 */
public class autoRightScale extends CommandGroup {


	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public autoRightScale() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
		addSequential(new clawClose());						//tighten grip on cube
		addSequential(new elevatorAuto(.5, .5));			//lower elevator to drop cube
		addParallel(new elevatorAuto(-1.0, 7));			//raise elevator to correct height
		addSequential(new driveAutonomous(.12, -.7, 4.5)); 		//drive forward to scale
		addSequential(new driveAutonomous(.12, -.45, 1)); 		//drive forward to scale (Slow)
		addSequential(new driveAutonomous(-.7, 0, .8));		//rotate 90 degrees left
		addSequential(new driveAutonomous(.12, -.5, .6));	//drive over scale
		addSequential(new clawOpen());					//open claw to release cube
		addSequential(new driveAutonomous(.12, .7, 1));	//drive back from scale

    }

}
