// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1591.Powerup.commands;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc1591.Powerup.subsystems.*;

/**
 *
 */
public class autoLeft extends CommandGroup {


	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public autoLeft() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
//    	String gameData;
//    	gameData = DriverStation.getInstance().getGameSpecificMessage();
//    	System.out.println(gameData);
//    	if (gameData.length( )> 0) {
//    		if (gameData.charAt(0) == 'L') {
//    			autoLeftSwitch(); 
//    		}
//    		else if (gameData.charAt(1) == 'L'){
//    			autoLeftScale();
//    		}
//    		else {
//    			autoLeftNeither();
//    		}
//    		
//    	}
//        // Add Commands here:
//        // e.g. addSequential(new Command1());
//        //      addSequential(new Command2());
//        // these will run in order.
//
//        // To run multiple commands at the same time,
//        // use addParallel()
//        // e.g. addParallel(new Command1());
//        //      addSequential(new Command2());
//        // Command1 and Command2 will run in parallel.
//
//        // A command group will require all of the subsystems that each member
//        // would require.
//        // e.g. if Command1 requires chassis, and Command2 requires arm,
//        // a CommandGroup containing them would require both the chassis and the
//        // arm.
//        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
//
//    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
// 
//    }
//
//	private void autoLeftScale() {		//test values to see what values we need
//		addSequential(new clawClose());						//tighten grip on cube
//		addSequential(new elevatorAuto(.5, .5));			//lower elevator to drop cube
//		addParallel(new elevatorAuto(-1.0, 7));			//raise elevator to correct height
//		addSequential(new driveAutonomous(.1, -.7, 5.5)); 		//drive forward to scale
//		addSequential(new driveAutonomous(.7, 0, .8));		//rotate 90 degrees right
//		addSequential(new driveAutonomous(.1, -.7, .6));	//drive over scale
//		addSequential(new clawOpen());					//open claw to release cube
//		addSequential(new driveAutonomous(.1, .7, 1));	//drive over scale
//		
//	}
//
//	private void autoLeftSwitch() {	//test values to see what  values we need
//		addSequential(new clawClose());						//tighten grip on cube
//		addSequential(new elevatorAuto(.5, .5));			//lower elevator to drop cube
//		addParallel(new elevatorAuto(-1.0, 1));				//raise elevator to correct height
//		addSequential(new driveAutonomous(.1, -.7, 2.2)); 		//drive forward to switch
//		addSequential(new driveAutonomous(.7, 0, .8));		//rotate 90 degrees right
//		addSequential(new driveAutonomous(.1, -.7, .6));	//drive over switch
//		addSequential(new clawOpen());						//open claw to release cube
//		
//	}
//	private void autoLeftNeither() {	//test values to see what  values we need
//		addSequential(new clawClose());						//tighten grip on cube
//		addSequential(new driveAutonomous(.1, -.7, 5)); 		//drive forward between switch and scale
//		addSequential(new driveAutonomous(.7, 0, 1.5));		//rotate 90 degrees right
//		addSequential(new driveAutonomous(.1, -.7, 1.5));	//drive forward to get ready
//		addSequential(new elevatorAuto(.5, .5));			//lower elevator to drop cube
//		addSequential(new elevatorAuto(-1.0, 7));				//raise elevator to correct height		
    	}
}
