// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1591.Powerup.commands;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc1591.Powerup.subsystems.*;

/**
 *
 */
public class autoRightSwitch extends CommandGroup {


	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public autoRightSwitch() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
		addSequential(new clawClose());						//tighten grip on cube
		addSequential(new elevatorAuto(.5, .5));			//lower elevator to drop cube
		addParallel(new elevatorAuto(-1.0, 1));				//raise elevator to correct height
		addSequential(new driveAutonomous(.1, -.7, 2.3)); 	//drive forward to switch
		addSequential(new driveAutonomous(-.7, 0, .9));		//rotate 90 degrees left
		addSequential(new driveAutonomous(.1, -.7, 1.1));	//drive over switch
		addSequential(new clawOpen());						//open claw to release cube

    }

}
